//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektNutrition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_FoodDay
    {
        public int id { get; set; }
        public int Product_id { get; set; }
        public int FoodDay_id { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> count { get; set; }
        public double caloric { get; set; }
        public double protein { get; set; }
        public double carb { get; set; }
        public double fat { get; set; }
    
        public virtual FoodDay FoodDay { get; set; }
        public virtual Product Product { get; set; }
    }
}
